spring:
  application:
    name: eCommerceSystem
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 86400
    refreshTokenExpiration: 604800
  profiles:
    active: dev
stripe :
  secretKey : ${STRIPE_SECRET_KEY}
  webhooksecretkey: ${STRIPE_WEBHOOK_SECRET_KEY}
